### PR TITLE
Smartcons

### PR DESCRIPTION
**Pull request by dangabhi**

### CODE REVIEW

**Comment by piyush-kurur** [comment]
The autobuild has failed. It looks like the coqdoc command is the one that failed, which means that there is some formattting issues in the comments. Please check it.

**Comment by dangabhi** [comment]
I am guessing commits of such nature will be squashed at some point. I squash them before pushing?

**Comment by piyush-kurur** [comment]
On Tue, Nov 29, 2016 at 02:27:25AM -0800, dangabhi wrote:
> I am guessing commits of such nature will be squashed at some point. I squash them before pushing?

It is okey to have them as long as it is small and does the obvious
(no need to squash them).  What is problematic is commits that are big
and do a lot of stuff at different places. That needs proper commit
messages/

**Comment by dangabhi** [comment]
Just noticed that Arch.v is not included in the _CoqProject (carried over from the _CoqProject in upstream). Consequently, there is stuff in there that does not compile with the current Types.v. The file itself will be changed with the next change for functions etc.; could maybe let it lie as is for now.

**Pull request merged**
