### PR TITLE
Machine

### PR DESCRIPTION
**Pull request by dangabhi**
Proofs in DecFacts could be written better, but they work for now. An inversion_sigma like tactic to use inj_pair2_eq_dec automatically on sigT equalities in context might be possible.

### CODE REVIEW

**Comment by dangabhi** [comment]
Also, lt_unique in DecFacts is currently an axiom. Since that is not in standard libraries, I am not sure how to link to that.

**Comment by dangabhi** [comment]
I had checked that yesterday and it was a tactic failure (injection with a Prop constructor not going through), and not a usual missing underscore. I have since opam switched once or twice, and have not been able to compile with 8.5.2 again.

**Comment by piyush-kurur** [comment]
On Sun, Feb 25, 2018 at 10:35:45PM -0800, dangabhi wrote:
> I had checked that yesterday and it was a tactic failure (injection
> with a Prop constructor not going through), and not a usual missing
> underscore. I have since opam switched once or twice, and have not
> been able to compile with 8.5.2 again.


So can you get it fixed so that I can merge.

**Comment by dangabhi** [comment]
In 8.5.2 the 'congruence' tactic does not prove `word n <> word n0` from `n <> n0`.
I can do it with an 'inversion 1; contradiction'; but if things like this change version to version, does it make too much sense to provide compatibility?

**Comment by dangabhi** [comment]
I might have jumped the gun with committing (pun) to the possibility of arg_eq_dec freedom.
I had tried a small experiment with a non-dependent reg inside a non-dependent arg. With our Types, I still need to use most of the stuff that went into arg_eq_dec for the definitions. 
To be fair, I still avoid having to prove eq_dec on 'index', which was causing most of the compatibility and CoLoR library usage issues. If that is still a win, then we can stick to this way of doing things.

**Comment by piyush-kurur** [comment]
I will merge this after you are here.

**Pull request merged**
